logging.level.com.github.oliverlj: DEBUG

spring.http.converters.preferred-json-mapper: json-api

spring.json-api:
  enable-serialization-options: INCLUDE_RELATIONSHIP_ATTRIBUTES
  disable-deserialization-options: REQUIRE_RESOURCE_ID
